name: RPGSkill
version: '${project.version}'
main: com.outcast.rpgskill.RPGSkill
api-version: 1.19
depend: [ RPGCore ]
authors: [ Hexacorx ]
description: The skill plugin that will allow users to cast skills learned by progression through their classes.
website: www.outcastrpg.com
